version: 0.3.0
name: gifencoder
description: A library for creating gif files, including animated gifs.
homepage: https://github.com/google/dart-gif-encoder
authors:
- Brian Slesinsky <brian-web@slesinsky.org>
- Jimmy Forrester-Fellowes <jimmyff@jimmyff.uk>

environment:
  sdk: '>=2.0.0-dev.61.0 <3.0.0'

dev_dependencies:
  build_runner: ^0.9.2
  build_test: ^0.10.3+1
  build_web_compilers: ^0.4.1
  test: ^1.3.0
